version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run: docker pull lorf/test-docker-image
      - run: docker build --cache-from=lorf/test-docker-image -t lorf/test-docker-image .
      - run: docker images
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker push lorf/test-docker-image
