version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      BUILD_IMAGE: lorf/test-docker-image
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker pull "$BUILD_IMAGE" || true
          docker build --cache-from="$BUILD_IMAGE" -t "$BUILD_IMAGE" .
          docker images
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push "$BUILD_IMAGE"
